In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,5,6]])


In [4]:
a.shape

(2, 3)

In [5]:
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
e = np.eye(3,3,3)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
A  = np.eye(3,4,1)
A[0,0]=2
A[1,1]=2
A[2,2]=2
print(A)


[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [15]:
A[0,0]=2

In [16]:
print(A)


[[2. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
B = A.T

In [20]:
print(B)

[[2. 0. 0.]
 [1. 2. 0.]
 [0. 1. 2.]
 [0. 0. 1.]]


In [21]:
C = B.flatten()

In [22]:
print(C)

[2. 0. 0. 1. 2. 0. 0. 1. 2. 0. 0. 1.]


In [24]:
D = B.reshape(6,2)

In [25]:
print(D)

[[2. 0.]
 [0. 1.]
 [2. 0.]
 [0. 1.]
 [2. 0.]
 [0. 1.]]


In [27]:
A.std()

0.82915619758885

In [28]:
import pandas as pd 

In [29]:
data = pd.read_csv('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')

In [30]:
data.head()

medv     crim    zn  chas    nox     rm     dis
0  24.0  0.00632  18.0     0  0.538  6.575  4.0900
1  21.6  0.02731   0.0     0  0.469  6.421  4.9671
2  34.7  0.02729   0.0     0  0.469  7.185  4.9671
3  33.4  0.03237   0.0     0  0.458  6.998  6.0622
4  36.2  0.06905   0.0     0  0.458  7.147  6.0622

In [ ]:
arr = ((0, -0.5), (1, 0), (0, 0.5), (0, 1.5), (1, 2.5), (2,3))

def sqerr(a, b):
    return (a - b)**2

def abserr(a, b):
    return abs(a - b)

def errsum(err_fun):
    return sum(list(map(lambda pair: err_fun(pair[0], pair[1]), arr)))

print(str(max(errsum(abserr), errsum(sqerr))))