In [28]:
import torch
import numpy as np

In [18]:
x = torch.Tensor(2, 3)
print(x)

tensor([[4.6400e-10, 4.5911e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [14]:
z = torch.rand(2, 3)
print(z)

tensor([[0.7405, 0.6083, 0.8714],
        [0.7998, 0.6754, 0.9855]])


In [19]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [26]:
w = torch.rand(2, 3)
print(w)
e = torch.rand(2, 3)
print(e)
print(e+w)

tensor([[0.4844, 0.4886, 0.3624],
        [0.3421, 0.4112, 0.0420]])
tensor([[0.1835, 0.8172, 0.5903],
        [0.5177, 0.1332, 0.5607]])
tensor([[0.6679, 1.3059, 0.9527],
        [0.8598, 0.5444, 0.6027]])


In [27]:
print(2*a)

tensor([[2., 2.],
        [2., 2.]])


In [34]:
a[:,0] = a[:,1] - 1

In [35]:
print(a)

tensor([[1., 2.],
        [1., 2.]])


In [44]:
x = torch.ones((2, 2), requires_grad=True)* 2

In [48]:
print(x)
z = x

tensor([[2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)


In [58]:
x = torch.ones((2, 2), requires_grad=True)*2
z = 2 * (x * x) + 5 * x
z.backward(torch.ones(2, 2))
print(x.grad)

None
